### PR TITLE
[WIP] Software compensation minimization binary

### PR DESCRIPTION
**Pull request by rete**
Added : 
- PandoraPFACalibrate_SoftwareCompensation binary to calibrate software compensation weights
- Original macro from Lan doing the same thing (will be removed on PR merging)

### CODE REVIEW

**Comment by StevenGreen1** [comment]
Hi Remi,

I'm happy for the software compensation weight training code to go into LCPandoraAnalysis, but just want to check with John, Andre and Frank that they are also happy with this before merging the pull request.

Thanks 

Steve

**Comment by gaede** [comment]
Perfectly fine with me.

**Comment by PandoraPFA** [comment]
I'm also happy to have all these (related) tools in one consolidated location.

Does the documentation need an update, though? There is presumably already good documentation for software compensation, which might just need a quick tidy up, and then can be added to the material accompanying LCPandoraAnalysis.

**Comment by StevenGreen1** [comment]
Hi Everyone,

I believe that in terms of what software compensation does, the documentation is very good (i.e. the arXiv paper and in the not too distant future my thesis).  In terms of how to use the binary, I'm not sure there is any documentation for this.  It would be worthwhile trying to make a few notes on this (Remi would you be happy to make a brief tex document showing how to use the binary that we could include in the LCPandoraAnalysis doc folder?).

Thanks 

Steve

**Comment by rete** [comment]
Hi all,

Indeed, a few words in the doc would be better to run this new binary. 
I'm actually facing problem with the results obtain after minimization using the binary. First thing : it seems that the full energy correction in LCContent is not the same as applied in this binary : 
[https://github.com/PandoraPFA/LCContent/blob/master/src/LCPlugins/LCSoftwareCompensation.cc#L36](https://github.com/PandoraPFA/LCContent/blob/master/src/LCPlugins/LCSoftwareCompensation.cc#L36)
There is an additional CleanCluster() call after applying software compensation weights that correct for the ecal energy. This is actually changing the behavior of the SC. I think we should add this CleanCluster() call in the minimization code.
What do you think ?

Remi

**Comment by StevenGreen1** [comment]
Hi Remi,

You are indeed correct, the original script does not account for the affect of the CleanClusters energy correction.  Applying CleanClusters outside of the Pandora framework is quite difficult as CleanClusters requires information about the pseduolayer that each of the hits is in, which isn't included in the training root files.  However, in https://github.com/PandoraPFA/LCContent/blob/daaed272489d354e290d9857fa3a49bcf4d3d505/src/LCPlugins/LCSoftwareCompensation.cc#L82, it can be seen that CleanClusters is only applied to hits in the ECal, therefore, maybe it would be more feasible to train software compensation on clusters with no energy deposits in the ECal?  

If this looks unfeasible then it is possible to included the pseudolayer as another variable in the training tree, but this would require modification of the training algorithm too. 

Cheers

Steve

**Comment by rete** [comment]
Selecting showers only contained in the HCal doesn't seem feasible as the minimization requires energies from 10 to 90 GeV. In the cases of high energies, it will be difficult to cut on ECal energy deposit and to do not have HCal leakage at the same time. I would opt for modifying the training algorithm instead.

**Comment by StevenGreen1** [comment]
Hi Remi,

I'm happy to discuss this with John later in the week to see if it is feasible to get the pseudolayer information (and anything else clean clusters uses) written out as apart of the training algorithm and then to get back to you.

In the mean time I have spotted a, hopefully small, error in the script you modified from Lan's original.  When applying software compensation you have parameterised the weights as a function of the  energy of the PFO when in fact it should be parameterised as the energy of the cluster.  

Effectively, this just means changing line:

https://github.com/rete/LCPandoraAnalysis/blob/c75b7a0ae044b79b5e3e63e75f9eb659a5c59d42/calibration/PandoraPFACalibrate_SoftwareCompensation.cc#L756

to read the "RawEnergyOfCluster" branch instead of the "EnergyOfPfo" branch.  You may also wish to update a few variables in your script based on this change.  I hope that doesn't take too long to do and I will get back to you later this week.

Cheers

Steve

**Comment by rete** [comment]
Thanks for spotting this ! I have checked the two distributions and they don't show some much difference. But indeed, it would make more sense to use  "RawEnergyOfCluster" instead of "EnergyOfPfo". I will commit this before merging the PR.

**Comment by rete** [comment]
Hi all,

today I received the output from the software compensation minimization binary using the monte carlo production sample with ilcsoft v01-19-04. The following plots show : 

- the total reconstructed energy before minimization : [SoftCompTotalEnergy.pdf](https://github.com/PandoraPFA/LCPandoraAnalysis/files/1280420/SoftCompTotalEnergy.pdf)
- the compensated energy using the current default weights in LCContent library : [SoftCompCompensatedEnergy_Current.pdf](https://github.com/PandoraPFA/LCPandoraAnalysis/files/1280419/SoftCompCompensatedEnergy_Current.pdf)
- the compensated energy using the new weights obtained after minimization : [SoftCompCompensatedEnergy_New.pdf](https://github.com/PandoraPFA/LCPandoraAnalysis/files/1280421/SoftCompCompensatedEnergy_New.pdf)

The values of the weights are the following : 
- Current ones : 
    2.49632
    -0.0697302
    0.000946986
    -0.112311
    0.0028182
    -9.62602e-05
    0.168614
    0.224318
    -0.0872853
- New ones : 
    2.34723
    -0.152547
    0.00370717
    0.0420014
    -0.00311419
    -0.000305323
    1.35319e-06
    1.66491e-06
    -1.02922

The values are quite different from each others and some values flipped to negative ...
Last week I also also obtained similar values by minimizing with lower statistics. These weights were used for obtaining new JER curves, but the results are really bad ...
Example with 30 GeV jets : [Total_JER_30GeV_WrongSoftComp.pdf](https://github.com/PandoraPFA/LCPandoraAnalysis/files/1280443/Total_JER_30GeV_WrongSoftComp.pdf)

Thoughts about all of this : 
- The minimization code is wrong somewhere
- The effect of ecal CleanCluster() correction should be included

Do you have any idea of what could be wrong ?

**Comment by StevenGreen1** [comment]
Hi Remi,  

This is unusual indeed.  I think you're thoughts sound very sensible.  I spoke to John yesterday and agrees that the training should include the CleanClusters logic.  Therefore, I will try and move all the necessary information to the root files and check that the logic matches what is in the LCContent library.  I will try and get this done today to see if this is the cause of the problem.  I will also generate some DD4HEP neutral kaon samples to examine myself.  

Can I check which detector model you are using?  I understand from Frank that, in ilcsoft v01-19-04, ILD o1 v05 no longer works out of the box in terms of the steering (taken from ILDConfig).  If you are using modified steering from ILDConfig/StandardConfig/lcgeo_current/bbudsc_3evt_stdreco_dd4hep.xml can you let me have a copy of that please?

Thanks

Steve

**Comment by rete** [comment]
Hi all,

I finally found what was wrong. I have an option in this binary to decide whether the compensated energy has to be computed with the MC energy or the cluster energy during the minimization process. The previous results were obtained using the cluster energy contrary to what has been done in the past. The JER looks now good by using the mc energy instead. I will change the option to use by default the true energy instead of the cluster energy in the incoming commits.
For the JER curves, I'm waiting for the last jobs to finish and I will provide them asap before merging the PR (just for validation).
Nevertheless, I think that the minimization should take into account what is done in the CleanCluster() function. This could be done in a future PR.
What do you think ?
 
Cheers,
Remi

**Comment by StevenGreen1** [comment]
Hi Remi,

That is good news.  I'm glad you were able to find the source of the problem.  I'm currently moving the clean clusters logic over to the binary you created so that this can be included in this pull request.  I hope to be done shortly, but will keep you informed.  Could you confirm the detector model you are using please?

Cheers

Steve

**Comment by rete** [comment]
I'm using the ILD detector ILD_l4_v02 from the lcgeo repository.
Good news for the CleanCluster logic inclusion in this PR !
Cheers, Remi

**Comment by rete** [comment]
Hi Steve,

There was an issue in your code, a variable misspelled in CleanCluster(). I readjusted it wrt what is implemented in LCContent. Can you validate that, just to be sure ?

Cheers, Remi

**Comment by StevenGreen1** [comment]
Hi Remi,

That change is very minimal and should make no big difference to the performance of the algorithm.  I did change the name of that variable from correctedHadronicEnergy (as in LCContent) to clusterHadronicEnergy because correctedHadronicEnergy is the variable name used when implementing all energy correction functions in Pandora (i.e. CleanClusters, SoftwareCompensation, ScaleHotHadrons) and I just wanted to distinguish this specific instance where it is being used outside Pandora.  Of course it makes no difference really and I'm happy for it to be changed back to  correctedHadronicEnergy.

Have you tested this modified script (i.e. with CleanClusters) to obtain new software compensation weights for ILD_l4_v02?  The LCContent library has been updated so running the training algorithm with the master LCContent will produce the extra variables in the training files that are needed for the CleanClusters logic.  If you have and the weights are good then I'm happy to merge this pull request.  

Cheers

Steve

**Comment by rete** [comment]
I'm currently recompiling PandoraPFA and DDMarlinPandora. I will then have to re run the whole reco chain on the kaon0L samples which may take some time. I will post more plots and info asap.

**Comment by StevenGreen1** [comment]
Hi Remi,

That sounds good, no rush on the timing for this though.  

Cheers

Steve

**Comment by rete** [comment]
Hi Cambridge,

the [latest JER plot](https://user-images.githubusercontent.com/950347/30328269-5b17aed6-97be-11e7-86d1-d9812337023f.png) (in red) I got this morning show almost the same JER as before but linearity was improved.
I updated the documentation in the doc directory to explain how to use the new binary. I also change to default option for using or not the true energy in the chi2 computation. By default, the true energy is used, which is coherent with previous work on SC.

I think that at this point, the PR can be merged except if you have additional remarks or requests.

Pinging @gaede for latest JER plot.

Cheers, Rémi

**Comment by StevenGreen1** [comment]
Hi Remi,

That works looks excellent.  Thank you for providing the JER plot for validation and for updating the documentation, which is always extremely useful.  Everything looks great and I'll merge the pull request now.

Cheers

Steve

**Pull request merged**
