### PR TITLE
Ignore warnings from external header files

### PR DESCRIPTION
**Pull request by andresailer**

### CODE REVIEW

**Comment by PandoraPFA** [comment]
It's a rather aggressive strategy to ignore warnings from all external packages, rather than just specific packages with which there are known issues!

**Comment by andresailer** [comment]
We are also aggressively setting as many warning flags as possible and except for ROOT we get the warnings when building our own packages, which should be enough.

**Comment by gaede** [comment]
As mentioned before: there are of course potentially cases where warnings are only created in included header files when using them in the dependent package. These we will never catch with these settings ...
Proper solution would be to get rid of all warnings, which is still quite some work ...

**Comment by PandoraPFA** [comment]
Well you (obviously) know exactly what you are doing here anyhow :) We're very happy to let you manage the LCPandoraAnalysis build tools/config as you see best.

Any future requests for changes to the build for the core Pandora libraries are potentially more complicated though, and need to be thought through in some detail, to balance LAr TPC use (and politics!) too.

Thanks!

**Pull request merged**
